[project]
name = "bujo"
version = "0.1.0"
description = "A service to text your bujo page and will create relevant cal events and tasks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.5.3",
]
